// Shared one-click theme presets for WhatsApp Themes.
// Loaded as a classic script, so values are exposed on window.WAThemeShared.
(() => {
  'use strict';

  const presets = Object.freeze([
    Object.freeze({
      name: 'AMOLED',
      tag: 'Pure dark',
      values: Object.freeze({
        outBubbleColor: '#075e54',
        inBubbleColor: '#111111',
        headerColor: '#050505',
        sidebarColor: '#050505',
        sidebarTintColor: '#000000',
        sidebarTintOpacity: 0,
        navStripColor: '#050505',
        chatlistHeaderColor: '#050505',
        chatCardBgColor: '#101010',
        outBubbleOpacity: 96,
        inBubbleOpacity: 92,
        convHeaderOpacity: 94,
        chatlistHeaderOpacity: 92,
        navStripOpacity: 94,
        chatCardOpacity: 86,
        fontSize: 14,
      }),
    }),
    Object.freeze({
      name: 'Glass Blur',
      tag: 'Wallpaper first',
      values: Object.freeze({
        outBubbleColor: '#128c7e',
        inBubbleColor: '#1f2c33',
        headerColor: '#1f2c33',
        sidebarTintColor: '#111b21',
        sidebarTintOpacity: 22,
        sidebarColor: '#111b21',
        navStripColor: '#1f2c33',
        chatlistHeaderColor: '#1f2c33',
        chatCardBgColor: '#1f2c33',
        outBubbleOpacity: 74,
        inBubbleOpacity: 70,
        convHeaderOpacity: 72,
        convHeaderBlur: 14,
        chatlistHeaderOpacity: 68,
        chatlistHeaderBlur: 14,
        navStripOpacity: 64,
        navStripBlur: 12,
        chatCardOpacity: 58,
        chatCardBlurIntensity: 10,
        blurIntensity: 12,
        sidebarBlurIntensity: 14,
      }),
      checks: Object.freeze({
        blurOutBubble: true,
        blurInBubble: true,
        blurSidebar: true,
        chatCardBlur: true,
      }),
    }),
    Object.freeze({
      name: 'Neon Green',
      tag: 'Cyber WA',
      values: Object.freeze({
        outBubbleColor: '#00a884',
        inBubbleColor: '#172027',
        headerColor: '#06261f',
        sidebarColor: '#061b18',
        sidebarTintColor: '#00a884',
        sidebarTintOpacity: 10,
        navStripColor: '#061b18',
        chatlistHeaderColor: '#06261f',
        chatCardBgColor: '#09241f',
        outBubbleOpacity: 100,
        inBubbleOpacity: 90,
        convHeaderOpacity: 96,
        chatlistHeaderOpacity: 96,
        navStripOpacity: 100,
        chatCardOpacity: 88,
        fontSize: 14,
      }),
    }),
    Object.freeze({
      name: 'Midnight Purple',
      tag: 'Soft premium',
      values: Object.freeze({
        outBubbleColor: '#6d5dfc',
        inBubbleColor: '#29233a',
        headerColor: '#201a31',
        sidebarColor: '#15111f',
        sidebarTintColor: '#6d5dfc',
        sidebarTintOpacity: 12,
        navStripColor: '#181225',
        chatlistHeaderColor: '#201a31',
        chatCardBgColor: '#211b31',
        outBubbleOpacity: 92,
        inBubbleOpacity: 86,
        convHeaderOpacity: 94,
        chatlistHeaderOpacity: 92,
        navStripOpacity: 94,
        chatCardOpacity: 82,
        fontSize: 14,
      }),
    }),
    Object.freeze({
      name: 'Sakura',
      tag: 'Soft pink',
      values: Object.freeze({
        outBubbleColor: '#d95d8f',
        inBubbleColor: '#30242b',
        headerColor: '#33202a',
        sidebarColor: '#1f171d',
        sidebarTintColor: '#d95d8f',
        sidebarTintOpacity: 10,
        navStripColor: '#261922',
        chatlistHeaderColor: '#33202a',
        chatCardBgColor: '#2b2028',
        outBubbleOpacity: 92,
        inBubbleOpacity: 86,
        convHeaderOpacity: 94,
        chatlistHeaderOpacity: 92,
        navStripOpacity: 96,
        chatCardOpacity: 84,
        fontSize: 14,
      }),
    }),
    Object.freeze({
      name: 'Minimal Grey',
      tag: 'Clean',
      values: Object.freeze({
        outBubbleColor: '#3a4a54',
        inBubbleColor: '#242626',
        headerColor: '#202c33',
        sidebarColor: '#111b21',
        sidebarTintColor: '#111b21',
        sidebarTintOpacity: 0,
        navStripColor: '#202c33',
        chatlistHeaderColor: '#202c33',
        chatCardBgColor: '#1d1f1f',
        outBubbleOpacity: 92,
        inBubbleOpacity: 92,
        convHeaderOpacity: 100,
        chatlistHeaderOpacity: 100,
        navStripOpacity: 100,
        chatCardOpacity: 100,
        fontSize: 14,
      }),
    }),
  ]);

  window.WAThemeShared = Object.freeze({
    ...(window.WAThemeShared || {}),
    presets,
  });
})();
